# Generated by Django 3.2 on 2022-12-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0003_auto_20221214_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userface',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
